site_name: SBMLKinetics
site_url: https://github.com/ModelEngineering/kinetics_validator
site_description: Description...
site_author:      Jin Xu
 
docs_dir: '_build'

theme: readthedocs

nav:
    - Home: html/index.html
